<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\CeoAgent.Integrations\CeoAgent.Integrations.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Agents.AI.Abstractions" Version="1.6.2" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="Meziantou.Analyzer" Version="3.0.94" />
  </ItemGroup>
</Project>
