// <auto-generated />
using System;
using System.Collections.Generic;
using CeoAgent.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CeoAgent.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CeoAgentDbContext))]
    partial class CeoAgentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CeoAgent.Infrastructure.Entities.AgentProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("display_name");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("language");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("model_name");

                    b.Property<string>("PromptOverride")
                        .HasColumnType("text")
                        .HasColumnName("prompt_override");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_agent_profile");

                    b.HasIndex("CompanyId")
                        .IsUnique()
                        .HasDatabaseName("ix_agent_profile_company_id");

                    b.ToTable("agent_profile", "public");
                });

            modelBuilder.Entity("CeoAgent.Infrastructure.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("time_zone_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "WorkingHours", "CeoAgent.Infrastructure.Entities.Company.WorkingHours#WorkingHours", b1 =>
                        {
                            b1.ComplexCollection(typeof(List<Dictionary<string, object>>), "Holidays", "CeoAgent.Infrastructure.Entities.Company.WorkingHours#WorkingHours.Holidays#SpecialDay", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<DateOnly>("Date")
                                        .HasJsonPropertyName("date");

                                    b2.Property<bool>("IsClosed")
                                        .HasJsonPropertyName("isClosed");

                                    b2.Property<string>("Reason")
                                        .HasJsonPropertyName("reason");

                                    b2.ComplexCollection(typeof(List<Dictionary<string, object>>), "TimeSlots", "CeoAgent.Infrastructure.Entities.Company.WorkingHours#WorkingHours.Holidays#SpecialDay.TimeSlots#TimeSlot", b3 =>
                                        {
                                            b3.IsRequired();

                                            b3.Property<TimeOnly>("End");

                                            b3.Property<TimeOnly>("Start");

                                            b3.HasJsonPropertyName("timeSlots");
                                        });

                                    b2.HasJsonPropertyName("holidays");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Schedule", "CeoAgent.Infrastructure.Entities.Company.WorkingHours#WorkingHours.Schedule#WeeklySchedule", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.ComplexCollection(typeof(List<Dictionary<string, object>>), "Friday", "CeoAgent.Infrastructure.Entities.Company.WorkingHours#WorkingHours.Schedule#WeeklySchedule.Friday#TimeSlot", b3 =>
                                        {
                                            b3.IsRequired();

                                            b3.Property<TimeOnly>("End");

                                            b3.Property<TimeOnly>("Start");

                                            b3.HasJsonPropertyName("friday");
                                        });

                                    b2.ComplexCollection(typeof(List<Dictionary<string, object>>), "Monday", "CeoAgent.Infrastructure.Entities.Company.WorkingHours#WorkingHours.Schedule#WeeklySchedule.Monday#TimeSlot", b3 =>
                                        {
                                            b3.IsRequired();

                                            b3.Property<TimeOnly>("End");

                                            b3.Property<TimeOnly>("Start");

                                            b3.HasJsonPropertyName("monday");
                                        });

                                    b2.ComplexCollection(typeof(List<Dictionary<string, object>>), "Saturday", "CeoAgent.Infrastructure.Entities.Company.WorkingHours#WorkingHours.Schedule#WeeklySchedule.Saturday#TimeSlot", b3 =>
                                        {
                                            b3.IsRequired();

                                            b3.Property<TimeOnly>("End");

                                            b3.Property<TimeOnly>("Start");

                                            b3.HasJsonPropertyName("saturday");
                                        });

                                    b2.ComplexCollection(typeof(List<Dictionary<string, object>>), "Sunday", "CeoAgent.Infrastructure.Entities.Company.WorkingHours#WorkingHours.Schedule#WeeklySchedule.Sunday#TimeSlot", b3 =>
                                        {
                                            b3.IsRequired();

                                            b3.Property<TimeOnly>("End");

                                            b3.Property<TimeOnly>("Start");

                                            b3.HasJsonPropertyName("sunday");
                                        });

                                    b2.ComplexCollection(typeof(List<Dictionary<string, object>>), "Thursday", "CeoAgent.Infrastructure.Entities.Company.WorkingHours#WorkingHours.Schedule#WeeklySchedule.Thursday#TimeSlot", b3 =>
                                        {
                                            b3.IsRequired();

                                            b3.Property<TimeOnly>("End");

                                            b3.Property<TimeOnly>("Start");

                                            b3.HasJsonPropertyName("thursday");
                                        });

                                    b2.ComplexCollection(typeof(List<Dictionary<string, object>>), "Tuesday", "CeoAgent.Infrastructure.Entities.Company.WorkingHours#WorkingHours.Schedule#WeeklySchedule.Tuesday#TimeSlot", b3 =>
                                        {
                                            b3.IsRequired();

                                            b3.Property<TimeOnly>("End");

                                            b3.Property<TimeOnly>("Start");

                                            b3.HasJsonPropertyName("tuesday");
                                        });

                                    b2.ComplexCollection(typeof(List<Dictionary<string, object>>), "Wednesday", "CeoAgent.Infrastructure.Entities.Company.WorkingHours#WorkingHours.Schedule#WeeklySchedule.Wednesday#TimeSlot", b3 =>
                                        {
                                            b3.IsRequired();

                                            b3.Property<TimeOnly>("End");

                                            b3.Property<TimeOnly>("Start");

                                            b3.HasJsonPropertyName("wednesday");
                                        });

                                    b2.HasJsonPropertyName("schedule");
                                });

                            b1
                                .ToJson("working_hours_json")
                                .HasColumnType("jsonb");
                        });

                    b.HasKey("Id")
                        .HasName("pk_company");

                    b.ToTable("company", "public");
                });

            modelBuilder.Entity("CeoAgent.Infrastructure.Entities.CompanyChannel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CredentialReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("credential_reference_id");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderChannelId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("provider_channel_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Metadata", "CeoAgent.Infrastructure.Entities.CompanyChannel.Metadata#ChannelMetadata", b1 =>
                        {
                            b1.IsRequired();

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Instagram", "CeoAgent.Infrastructure.Entities.CompanyChannel.Metadata#ChannelMetadata.Instagram#InstagramMetadata", b2 =>
                                {
                                    b2.Property<string>("IgUserId")
                                        .IsRequired()
                                        .HasJsonPropertyName("ig_user_id");

                                    b2.Property<string>("PageId")
                                        .HasJsonPropertyName("page_id");

                                    b2.HasJsonPropertyName("instagram");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Telegram", "CeoAgent.Infrastructure.Entities.CompanyChannel.Metadata#ChannelMetadata.Telegram#TelegramMetadata", b2 =>
                                {
                                    b2.Property<string>("BotUsername")
                                        .IsRequired()
                                        .HasJsonPropertyName("bot_username");

                                    b2.Property<long>("ChatId")
                                        .HasJsonPropertyName("chat_id");

                                    b2.HasJsonPropertyName("telegram");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "WhatsAppCloud", "CeoAgent.Infrastructure.Entities.CompanyChannel.Metadata#ChannelMetadata.WhatsAppCloud#WhatsAppCloudMetadata", b2 =>
                                {
                                    b2.Property<string>("BusinessAccountId")
                                        .IsRequired()
                                        .HasJsonPropertyName("business_account_id");

                                    b2.Property<string>("DisplayPhoneNumber")
                                        .HasJsonPropertyName("display_phone_number");

                                    b2.Property<string>("PhoneNumberId")
                                        .IsRequired()
                                        .HasJsonPropertyName("phone_number_id");

                                    b2.Property<string>("VerifiedName")
                                        .HasJsonPropertyName("verified_name");

                                    b2.HasJsonPropertyName("whatsapp_cloud");
                                });

                            b1
                                .ToJson("metadata_json")
                                .HasColumnType("jsonb");
                        });

                    b.HasKey("Id")
                        .HasName("pk_company_channel");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_company_channel_company_id");

                    b.HasIndex("CredentialReferenceId")
                        .HasDatabaseName("ix_company_channel_credential_reference_id");

                    b.HasIndex("Provider")
                        .HasDatabaseName("ix_company_channel_provider");

                    b.HasIndex("Provider", "ProviderChannelId")
                        .IsUnique()
                        .HasDatabaseName("ix_company_channel_provider_provider_channel_id");

                    b.ToTable("company_channel", "public");
                });

            modelBuilder.Entity("CeoAgent.Infrastructure.Entities.CompanyTool", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CredentialReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("credential_reference_id");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("ToolKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("tool_key");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Configuration", "CeoAgent.Infrastructure.Entities.CompanyTool.Configuration#ToolConfiguration", b1 =>
                        {
                            b1.Property<string>("ToolKey")
                                .IsRequired()
                                .HasJsonPropertyName("toolKey");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "CheckAvailability", "CeoAgent.Infrastructure.Entities.CompanyTool.Configuration#ToolConfiguration.CheckAvailability#CheckAvailabilityConfig", b2 =>
                                {
                                    b2.Property<int>("AdvanceBookingDays")
                                        .HasJsonPropertyName("advanceBookingDays");

                                    b2.Property<int>("MaxPartySize")
                                        .HasJsonPropertyName("maxPartySize");

                                    b2.Property<int>("MinPartySize")
                                        .HasJsonPropertyName("minPartySize");

                                    b2.Property<int>("SlotMinutes")
                                        .HasJsonPropertyName("slotMinutes");

                                    b2.HasJsonPropertyName("check_availability");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "GoogleCalendar", "CeoAgent.Infrastructure.Entities.CompanyTool.Configuration#ToolConfiguration.GoogleCalendar#GoogleCalendarConfig", b2 =>
                                {
                                    b2.Property<int>("BufferMinutes")
                                        .HasJsonPropertyName("bufferMinutes");

                                    b2.Property<string>("CalendarId")
                                        .IsRequired()
                                        .HasJsonPropertyName("calendarId");

                                    b2.Property<string>("TimeZoneId")
                                        .IsRequired()
                                        .HasJsonPropertyName("timeZoneId");

                                    b2.HasJsonPropertyName("google_calendar");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "RequestHumanHandoff", "CeoAgent.Infrastructure.Entities.CompanyTool.Configuration#ToolConfiguration.RequestHumanHandoff#RequestHumanHandoffConfig", b2 =>
                                {
                                    b2.Property<string>("EscalationChannel")
                                        .HasJsonPropertyName("escalationChannel");

                                    b2.PrimitiveCollection<string>("NotifyUsers")
                                        .IsRequired()
                                        .HasJsonPropertyName("notifyUsers");

                                    b2.Property<int>("TimeoutMinutes")
                                        .HasJsonPropertyName("timeoutMinutes");

                                    b2.HasJsonPropertyName("request_human_handoff");
                                });

                            b1
                                .ToJson("configuration_json")
                                .HasColumnType("jsonb");
                        });

                    b.HasKey("Id")
                        .HasName("pk_company_tool");

                    b.HasIndex("CredentialReferenceId")
                        .HasDatabaseName("ix_company_tool_credential_reference_id");

                    b.HasIndex("CompanyId", "ToolKey")
                        .IsUnique()
                        .HasDatabaseName("ix_company_tool_company_id_tool_key");

                    b.ToTable("company_tool", "public");
                });

            modelBuilder.Entity("CeoAgent.Infrastructure.Entities.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgentProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_profile_id");

                    b.Property<Guid>("CompanyChannelId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_channel_id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateTime>("LastMessageAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_message_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_conversation");

                    b.HasIndex("AgentProfileId")
                        .HasDatabaseName("ix_conversation_agent_profile_id");

                    b.HasIndex("CompanyChannelId")
                        .HasDatabaseName("ix_conversation_company_channel_id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_conversation_customer_id");

                    b.HasIndex("CompanyId", "CustomerId", "CompanyChannelId")
                        .IsUnique()
                        .HasDatabaseName("ix_conversation_company_id_customer_id_company_channel_id")
                        .HasFilter("status = 'Open'");

                    b.ToTable("conversation", "public");
                });

            modelBuilder.Entity("CeoAgent.Infrastructure.Entities.ConversationState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Snapshot", "CeoAgent.Infrastructure.Entities.ConversationState.Snapshot#ConversationStateSnapshot", b1 =>
                        {
                            b1.IsRequired();

                            b1.PrimitiveCollection<string>("ConversationFlags")
                                .IsRequired()
                                .HasJsonPropertyName("conversationFlags");

                            b1.Property<string>("CurrentIntent")
                                .HasJsonPropertyName("currentIntent");

                            b1.Property<string>("PendingAction")
                                .HasJsonPropertyName("pendingAction");

                            b1.Property<int>("TurnCount")
                                .HasJsonPropertyName("turnCount");

                            b1.ComplexCollection(typeof(List<Dictionary<string, object>>), "Slots", "CeoAgent.Infrastructure.Entities.ConversationState.Snapshot#ConversationStateSnapshot.Slots#ConversationSlot", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<bool?>("BooleanValue")
                                        .HasJsonPropertyName("booleanValue");

                                    b2.Property<DateOnly?>("DateValue")
                                        .HasJsonPropertyName("dateValue");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasJsonPropertyName("name");

                                    b2.Property<decimal?>("NumberValue")
                                        .HasJsonPropertyName("numberValue");

                                    b2.Property<string>("TextValue")
                                        .HasJsonPropertyName("textValue");

                                    b2.Property<TimeOnly?>("TimeValue")
                                        .HasJsonPropertyName("timeValue");

                                    b2.HasJsonPropertyName("slots");
                                });

                            b1
                                .ToJson("state_json")
                                .HasColumnType("jsonb");
                        });

                    b.HasKey("Id")
                        .HasName("pk_conversation_state");

                    b.HasIndex("ConversationId")
                        .IsUnique()
                        .HasDatabaseName("ix_conversation_state_conversation_id");

                    b.ToTable("conversation_state", "public");
                });

            modelBuilder.Entity("CeoAgent.Infrastructure.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyChannelId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_channel_id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("ExternalCustomerId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("external_customer_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_customer");

                    b.HasIndex("CompanyChannelId", "ExternalCustomerId")
                        .IsUnique()
                        .HasDatabaseName("ix_customer_company_channel_id_external_customer_id");

                    b.ToTable("customer", "public");
                });

            modelBuilder.Entity("CeoAgent.Infrastructure.Entities.IntegrationCredentialReference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("provider");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("purpose");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("reference");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Metadata", "CeoAgent.Infrastructure.Entities.IntegrationCredentialReference.Metadata#CredentialMetadata", b1 =>
                        {
                            b1.Property<string>("Provider")
                                .IsRequired()
                                .HasJsonPropertyName("provider");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "GoogleCalendar", "CeoAgent.Infrastructure.Entities.IntegrationCredentialReference.Metadata#CredentialMetadata.GoogleCalendar#GoogleCalendarCredentialMetadata", b2 =>
                                {
                                    b2.Property<string>("CalendarId")
                                        .IsRequired()
                                        .HasJsonPropertyName("calendarId");

                                    b2.Property<DateTimeOffset?>("ExpiresAt")
                                        .HasJsonPropertyName("expiresAt");

                                    b2.Property<string>("Scope")
                                        .IsRequired()
                                        .HasJsonPropertyName("scope");

                                    b2.HasJsonPropertyName("google_calendar");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "WhatsAppCloud", "CeoAgent.Infrastructure.Entities.IntegrationCredentialReference.Metadata#CredentialMetadata.WhatsAppCloud#WhatsAppCloudCredentialMetadata", b2 =>
                                {
                                    b2.Property<string>("AppId")
                                        .IsRequired()
                                        .HasJsonPropertyName("appId");

                                    b2.Property<string>("TokenVersion")
                                        .IsRequired()
                                        .HasJsonPropertyName("tokenVersion");

                                    b2.HasJsonPropertyName("whatsapp_cloud");
                                });

                            b1
                                .ToJson("metadata_json")
                                .HasColumnType("jsonb");
                        });

                    b.HasKey("Id")
                        .HasName("pk_integration_credential_reference");

                    b.HasIndex("CompanyId", "Provider", "Purpose")
                        .IsUnique()
                        .HasDatabaseName("ix_integration_credential_reference_company_id_provider_purpose");

                    b.ToTable("integration_credential_reference", "public");
                });

            modelBuilder.Entity("CeoAgent.Infrastructure.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("MessageText")
                        .HasColumnType("text")
                        .HasColumnName("message_text");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("ProviderMessageId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("provider_message_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Payload", "CeoAgent.Infrastructure.Entities.Message.Payload#MessagePayload", b1 =>
                        {
                            b1.Property<string>("ProviderMessageId")
                                .HasJsonPropertyName("providerMessageId");

                            b1.Property<string>("ProviderType")
                                .HasJsonPropertyName("providerType");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Audio", "CeoAgent.Infrastructure.Entities.Message.Payload#MessagePayload.Audio#AudioPayload", b2 =>
                                {
                                    b2.Property<string>("BlobUri")
                                        .IsRequired()
                                        .HasJsonPropertyName("blobUri");

                                    b2.Property<string>("ContentType")
                                        .IsRequired()
                                        .HasJsonPropertyName("contentType");

                                    b2.Property<int?>("DurationMs")
                                        .HasJsonPropertyName("durationMs");

                                    b2.Property<string>("Language")
                                        .HasJsonPropertyName("language");

                                    b2.Property<long>("SizeBytes")
                                        .HasJsonPropertyName("sizeBytes");

                                    b2.Property<string>("SttStatus")
                                        .HasJsonPropertyName("sttStatus");

                                    b2.Property<string>("TtsStatus")
                                        .HasJsonPropertyName("ttsStatus");

                                    b2.HasJsonPropertyName("audio");
                                });

                            b1
                                .ToJson("payload_json")
                                .HasColumnType("jsonb");
                        });

                    b.HasKey("Id")
                        .HasName("pk_message");

                    b.HasIndex("ConversationId")
                        .HasDatabaseName("ix_message_conversation_id");

                    b.HasIndex("CompanyId", "ProviderMessageId")
                        .IsUnique()
                        .HasDatabaseName("ix_message_company_id_provider_message_id")
                        .HasFilter("provider_message_id IS NOT NULL");

                    b.ToTable("message", "public");
                });

            modelBuilder.Entity("CeoAgent.Infrastructure.Entities.ToolExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<Guid>("CompanyToolId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_tool_id");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid?>("ResultMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("result_message_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("ToolKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("tool_key");

                    b.Property<Guid>("TriggerMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("trigger_message_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Request", "CeoAgent.Infrastructure.Entities.ToolExecution.Request#ToolExecutionRequest", b1 =>
                        {
                            b1.Property<string>("ToolKey")
                                .IsRequired()
                                .HasJsonPropertyName("toolKey");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "CheckAvailability", "CeoAgent.Infrastructure.Entities.ToolExecution.Request#ToolExecutionRequest.CheckAvailability#CheckAvailabilityRequest", b2 =>
                                {
                                    b2.Property<DateOnly>("Date")
                                        .HasJsonPropertyName("date");

                                    b2.Property<int>("PartySize")
                                        .HasJsonPropertyName("partySize");

                                    b2.Property<TimeOnly?>("PreferredTime")
                                        .HasJsonPropertyName("preferredTime");

                                    b2.HasJsonPropertyName("check_availability");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "CreateCalendarEvent", "CeoAgent.Infrastructure.Entities.ToolExecution.Request#ToolExecutionRequest.CreateCalendarEvent#CreateCalendarEventRequest", b2 =>
                                {
                                    b2.Property<DateTimeOffset>("End")
                                        .HasJsonPropertyName("end");

                                    b2.Property<DateTimeOffset>("Start")
                                        .HasJsonPropertyName("start");

                                    b2.Property<string>("Summary")
                                        .IsRequired()
                                        .HasJsonPropertyName("summary");

                                    b2.HasJsonPropertyName("create_calendar_event");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "RequestHumanHandoff", "CeoAgent.Infrastructure.Entities.ToolExecution.Request#ToolExecutionRequest.RequestHumanHandoff#RequestHumanHandoffRequest", b2 =>
                                {
                                    b2.Property<string>("Notes")
                                        .HasJsonPropertyName("notes");

                                    b2.Property<string>("Reason")
                                        .IsRequired()
                                        .HasJsonPropertyName("reason");

                                    b2.HasJsonPropertyName("request_human_handoff");
                                });

                            b1
                                .ToJson("request_json")
                                .HasColumnType("jsonb");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Result", "CeoAgent.Infrastructure.Entities.ToolExecution.Result#ToolExecutionResult", b1 =>
                        {
                            b1.Property<string>("ToolKey")
                                .IsRequired()
                                .HasJsonPropertyName("toolKey");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "CheckAvailability", "CeoAgent.Infrastructure.Entities.ToolExecution.Result#ToolExecutionResult.CheckAvailability#CheckAvailabilityResult", b2 =>
                                {
                                    b2.PrimitiveCollection<string>("AlternativeSlots")
                                        .IsRequired()
                                        .HasJsonPropertyName("alternativeSlots");

                                    b2.Property<bool>("Available")
                                        .HasJsonPropertyName("available");

                                    b2.Property<string>("UnavailabilityReason")
                                        .HasJsonPropertyName("unavailabilityReason");

                                    b2.HasJsonPropertyName("check_availability");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "CreateCalendarEvent", "CeoAgent.Infrastructure.Entities.ToolExecution.Result#ToolExecutionResult.CreateCalendarEvent#CreateCalendarEventResult", b2 =>
                                {
                                    b2.Property<string>("EventId")
                                        .IsRequired()
                                        .HasJsonPropertyName("eventId");

                                    b2.Property<string>("EventUrl")
                                        .IsRequired()
                                        .HasJsonPropertyName("eventUrl");

                                    b2.HasJsonPropertyName("create_calendar_event");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "RequestHumanHandoff", "CeoAgent.Infrastructure.Entities.ToolExecution.Result#ToolExecutionResult.RequestHumanHandoff#RequestHumanHandoffResult", b2 =>
                                {
                                    b2.Property<DateTimeOffset?>("EstimatedPickupAt")
                                        .HasJsonPropertyName("estimatedPickupAt");

                                    b2.Property<bool>("HandoffRequested")
                                        .HasJsonPropertyName("handoffRequested");

                                    b2.Property<string>("HandoffTicketId")
                                        .HasJsonPropertyName("handoffTicketId");

                                    b2.HasJsonPropertyName("request_human_handoff");
                                });

                            b1
                                .ToJson("result_json")
                                .HasColumnType("jsonb");
                        });

                    b.HasKey("Id")
                        .HasName("pk_tool_execution");

                    b.HasIndex("CompanyToolId")
                        .HasDatabaseName("ix_tool_execution_company_tool_id");

                    b.HasIndex("ConversationId")
                        .HasDatabaseName("ix_tool_execution_conversation_id");

                    b.HasIndex("ResultMessageId")
                        .HasDatabaseName("ix_tool_execution_result_message_id");

                    b.HasIndex("TriggerMessageId")
                        .HasDatabaseName("ix_tool_execution_trigger_message_id");

                    b.HasIndex("CompanyId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_tool_execution_company_id_idempotency_key");

                    b.ToTable("tool_execution", "public");
                });

            modelBuilder.Entity("CeoAgent.Infrastructure.Entities.AgentProfile", b =>
                {
                    b.HasOne("CeoAgent.Infrastructure.Entities.Company", "Company")
                        .WithOne("AgentProfile")
                        .HasForeignKey("CeoAgent.Infrastructure.Entities.AgentProfile", "CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_agent_profile_companies_company_id");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("CeoAgent.Infrastructure.Entities.CompanyChannel", b =>
                {
                    b.HasOne("CeoAgent.Infrastructure.Entities.Company", "Company")
                        .WithMany("Channels")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_company_channel_companies_company_id");

                    b.HasOne("CeoAgent.Infrastructure.Entities.IntegrationCredentialReference", "CredentialReference")
                        .WithMany("CompanyChannels")
                        .HasForeignKey("CredentialReferenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_company_channel_integration_credential_references_credentia");

                    b.Navigation("Company");

                    b.Navigation("CredentialReference");
                });

            modelBuilder.Entity("CeoAgent.Infrastructure.Entities.CompanyTool", b =>
                {
                    b.HasOne("CeoAgent.Infrastructure.Entities.Company", "Company")
                        .WithMany("Tools")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_company_tool_company_company_id");

                    b.HasOne("CeoAgent.Infrastructure.Entities.IntegrationCredentialReference", "CredentialReference")
                        .WithMany("CompanyTools")
                        .HasForeignKey("CredentialReferenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_company_tool_integration_credential_references_credential_r");

                    b.Navigation("Company");

                    b.Navigation("CredentialReference");
                });

            modelBuilder.Entity("CeoAgent.Infrastructure.Entities.Conversation", b =>
                {
                    b.HasOne("CeoAgent.Infrastructure.Entities.AgentProfile", "AgentProfile")
                        .WithMany("Conversations")
                        .HasForeignKey("AgentProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_conversation_agent_profile_agent_profile_id");

                    b.HasOne("CeoAgent.Infrastructure.Entities.CompanyChannel", "CompanyChannel")
                        .WithMany("Conversations")
                        .HasForeignKey("CompanyChannelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_conversation_company_channel_company_channel_id");

                    b.HasOne("CeoAgent.Infrastructure.Entities.Customer", "Customer")
                        .WithMany("Conversations")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_conversation_customers_customer_id");

                    b.Navigation("AgentProfile");

                    b.Navigation("CompanyChannel");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CeoAgent.Infrastructure.Entities.ConversationState", b =>
                {
                    b.HasOne("CeoAgent.Infrastructure.Entities.Conversation", "Conversation")
                        .WithOne("State")
                        .HasForeignKey("CeoAgent.Infrastructure.Entities.ConversationState", "ConversationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_conversation_state_conversation_conversation_id");

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("CeoAgent.Infrastructure.Entities.Customer", b =>
                {
                    b.HasOne("CeoAgent.Infrastructure.Entities.CompanyChannel", "CompanyChannel")
                        .WithMany("Customers")
                        .HasForeignKey("CompanyChannelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_customer_company_channel_company_channel_id");

                    b.Navigation("CompanyChannel");
                });

            modelBuilder.Entity("CeoAgent.Infrastructure.Entities.IntegrationCredentialReference", b =>
                {
                    b.HasOne("CeoAgent.Infrastructure.Entities.Company", "Company")
                        .WithMany("IntegrationCredentials")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_integration_credential_reference_company_company_id");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("CeoAgent.Infrastructure.Entities.Message", b =>
                {
                    b.HasOne("CeoAgent.Infrastructure.Entities.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_message_conversation_conversation_id");

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("CeoAgent.Infrastructure.Entities.ToolExecution", b =>
                {
                    b.HasOne("CeoAgent.Infrastructure.Entities.CompanyTool", "CompanyTool")
                        .WithMany("ToolExecutions")
                        .HasForeignKey("CompanyToolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tool_execution_company_tool_company_tool_id");

                    b.HasOne("CeoAgent.Infrastructure.Entities.Conversation", "Conversation")
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tool_execution_conversation_conversation_id");

                    b.HasOne("CeoAgent.Infrastructure.Entities.Message", "ResultMessage")
                        .WithMany("ResultToolExecutions")
                        .HasForeignKey("ResultMessageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_tool_execution_message_result_message_id");

                    b.HasOne("CeoAgent.Infrastructure.Entities.Message", "TriggerMessage")
                        .WithMany("TriggeredToolExecutions")
                        .HasForeignKey("TriggerMessageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tool_execution_message_trigger_message_id");

                    b.Navigation("CompanyTool");

                    b.Navigation("Conversation");

                    b.Navigation("ResultMessage");

                    b.Navigation("TriggerMessage");
                });

            modelBuilder.Entity("CeoAgent.Infrastructure.Entities.AgentProfile", b =>
                {
                    b.Navigation("Conversations");
                });

            modelBuilder.Entity("CeoAgent.Infrastructure.Entities.Company", b =>
                {
                    b.Navigation("AgentProfile");

                    b.Navigation("Channels");

                    b.Navigation("IntegrationCredentials");

                    b.Navigation("Tools");
                });

            modelBuilder.Entity("CeoAgent.Infrastructure.Entities.CompanyChannel", b =>
                {
                    b.Navigation("Conversations");

                    b.Navigation("Customers");
                });

            modelBuilder.Entity("CeoAgent.Infrastructure.Entities.CompanyTool", b =>
                {
                    b.Navigation("ToolExecutions");
                });

            modelBuilder.Entity("CeoAgent.Infrastructure.Entities.Conversation", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("State");
                });

            modelBuilder.Entity("CeoAgent.Infrastructure.Entities.Customer", b =>
                {
                    b.Navigation("Conversations");
                });

            modelBuilder.Entity("CeoAgent.Infrastructure.Entities.IntegrationCredentialReference", b =>
                {
                    b.Navigation("CompanyChannels");

                    b.Navigation("CompanyTools");
                });

            modelBuilder.Entity("CeoAgent.Infrastructure.Entities.Message", b =>
                {
                    b.Navigation("ResultToolExecutions");

                    b.Navigation("TriggeredToolExecutions");
                });
#pragma warning restore 612, 618
        }
    }
}
